Решение задания 3.2
Gulyashenko/TKI-141 pull request #23
Opened 2024-10-15 18:00 UTC by Gulyashenko

2024-10-21 11:34 UTC, MarinaPaley requested changes

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +double func_for_finding_summ_1(int n);
const

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +double func_for_finding_summ_2(int n, double e);
const
зачем int n?

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +double recurrent(int k);
const

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +}
`return 0;`

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +double func_for_finding_summ_1(int n) {
const

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	*/
Это документация. Убрать

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	*/
то же

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	double summ = 1.0;
почему?

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	for (int k = 0; k <= n; k++) {
k < n

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	double summ = 1.0;
Убрать

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	for (int k = 0; k <= n; k++) {
неверное условие

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	double summ = 1.0;
`double summ = 0.0;`

2024-10-21 11:34 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	}
неверно

2024-11-07 19:19 UTC, Gulyashenko commented on Tas3.2/Tas3.2.c
> +double func_for_finding_summ_2(int n, double e);
за тем, что порядковый номер элемента последовательности всегда целое число, и нет смысла выделять под него объём памяти необходимый для типа double или float, а точнее - лишний объём памяти

2024-11-11 12:13 UTC, MarinaPaley requested changes

2024-11-11 12:13 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +double func_for_finding_summ_2(const int n,const double e);
n в этой функции не используется

2024-11-11 12:13 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	for (int k = 0; current<e+DBL_EPSILON <= n; k++) {
по модулю

2024-11-11 12:13 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	return 1 / (double)(4 * k * k + 6 * k + 2);
знакопеременный ряд

2024-11-20 09:27 UTC, BalakinaEP requested changes

2024-11-20 09:27 UTC, BalakinaEP commented on Tas3.2/Tas3.2.c
> +	int n = input();
не проверяете, что введенное значение больше или равно 0

2024-11-20 09:27 UTC, BalakinaEP commented on Tas3.2/Tas3.2.c
> +	double e = input();
Введенное значение должно быть строго положительным

2024-11-20 09:27 UTC, BalakinaEP commented on Tas3.2/Tas3.2.c
> +	double summ = current;
Здесь `double summ = 0`. Так как мы прибавляем к сумме только то, что удовлетворяет условию

2024-11-20 09:27 UTC, BalakinaEP commented on Tas3.2/Tas3.2.c
> +	for (int k = 0; abs(current)>e-DBL_EPSILON; k++) {
`fabs(current)>e-DBL_EPSILON`

2024-11-20 09:27 UTC, BalakinaEP commented on Tas3.2/Tas3.2.c
> +		summ += current;
Поменять местами

2024-11-25 12:41 UTC, MarinaPaley requested changes

2024-11-25 12:41 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	if (n < 0 || e <= 0) {
`double` мы не сравниваем на строгое равенство
Уберите все проверки в функции ввода

2024-11-25 12:41 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	printf("конец первой функции");
убрать

2024-11-25 12:41 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	printf("конец второй функции");
убрать

2024-11-25 12:41 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	return pow(-1, k) / (double)(4 * k * k + 6 * k + 2);
`return -1.0 / (4 * k * k + 6 * k + 2);`

2024-11-25 13:54 UTC, MarinaPaley requested changes

2024-11-25 13:54 UTC, MarinaPaley commented on Tas3.2/Tas3.2.c
> +	if (scanf_s("%lf", &number) != 1 && number<=0+DBL_EPSILON) {
напишите отдельную функцию (обертку) на ввод неотрицательного числа

2024-11-25 14:15 UTC, MarinaPaley approved these changes

2024-12-07 23:33 UTC, merged